
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microtokenai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microtokenai
  minReplicas: 
  maxReplicas: 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 

