image:
  repository: myregistry/microtokenai-server
  tag: latest

env:
  MICROTOKENAI_SECRET_KEY: "my-secret-key"
  REDIS_HOST: "redis-service"
  REDIS_PORT: 6379
  AWS_STS_ENDPOINT: "https://sts.amazonaws.com"
  AZURE_GRAPH_ENDPOINT: "https://graph.microsoft.com/v1.0/me"
  GCP_IAM_ENDPOINT: "https://iam.googleapis.com/v1/projects/-/serviceAccounts/"
  FREE_TIER_EXPIRATION: 30
  PREMIUM_TIER_EXPIRATION: 60
  FREE_TIER_ANOMALY_RATE: 0.1
  PREMIUM_TIER_ANOMALY_RATE: 0.02
  ALLOWED_GEOLOCATIONS_FREE: "US,EU"

replicaCount: 3
service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

ingress:
  enabled: false
